### ISSUE TITLE
Suggestion: Dropdown icon and callback

### ISSUE THREAD

**Issue by cherrydev** [HITGIF/TextFieldBoxes#10]
If you're taking suggestions, I'd love it if there was an option to display a dropdown icon and the ability to set a callback for when it is clicked. I think the callback should include a reference to the TextFieldBox. I do not think it's necessary for the TextFieldBox to do more than this and the developer can handle what happens when it's clicked. For example, I would probably use a ListPopupWindow to display and select options.

**Comment by HITGIF** [comment]
I suppose you mean something like [this](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOejJsaVFBWnRXbUE/discoverable_dropdown.png) in which my job will only be making it possible to add an icon button at the end?
That'd be quite useful, since people can actually put other things there (mic icon etc.) So I'll be adding it in. Thanks for the suggestion :)

**Comment by cherrydev** [comment]
Yes, exactly! Perhaps just being able to programatically set an arbitrary View there would be perfect.

**Comment by HITGIF** [comment]
End Icon is now available in release 1.2.0 🎉🎉🎉
Check out README for more detail :)
